package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExcelUtil<M extends BaseExcelUtil<M>> extends Model<M> implements IBean {

	public void setName(java.lang.String name) {
		set("NAME", name);
	}

	public java.lang.String getName() {
		return get("NAME");
	}

	public void setRs(java.math.BigDecimal rows) {
		set("RS", rows);
	}

	public java.math.BigDecimal getRs() {
		return get("RS");
	}

	public void setCs(java.math.BigDecimal cols) {
		set("CS", cols);
	}

	public java.math.BigDecimal getCs() {
		return get("CS");
	}

}
