package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setTitle(java.lang.String title) {
		set("TITLE", title);
	}

	public java.lang.String getTitle() {
		return get("TITLE");
	}

	public void setContent(java.lang.String content) {
		set("CONTENT", content);
	}

	public java.lang.String getContent() {
		return get("CONTENT");
	}

}
