package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeighthardware<M extends BaseWeighthardware<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setWeiHardware(java.lang.String weiHardware) {
		set("WEI_HARDWARE", weiHardware);
	}

	public java.lang.String getWeiHardware() {
		return get("WEI_HARDWARE");
	}

	public void setBaseId(java.math.BigDecimal baseId) {
		set("BASE_ID", baseId);
	}

	public java.math.BigDecimal getBaseId() {
		return get("BASE_ID");
	}

	public void setFaIndex(java.lang.String faIndex) {
		set("FA_INDEX", faIndex);
	}

	public java.lang.String getFaIndex() {
		return get("FA_INDEX");
	}
	
	public void setWeightIndex(java.lang.String weightIndex) {
		set("WEIGHT_INDEX", weightIndex);
	}

	public java.lang.String getWeightIndex() {
		return get("WEIGHT_INDEX");
	}

}
