package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDoorhardware<M extends BaseDoorhardware<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setDoorHardware(java.lang.String doorHardware) {
		set("DOOR_HARDWARE", doorHardware);
	}

	public java.lang.String getDoorHardware() {
		return get("DOOR_HARDWARE");
	}

	public void setBaseId(java.math.BigDecimal baseId) {
		set("BASE_ID", baseId);
	}

	public java.math.BigDecimal getBaseId() {
		return get("BASE_ID");
	}

	public void setFaIndex(java.lang.String faIndex) {
		set("FA_INDEX", faIndex);
	}

	public java.lang.String getFaIndex() {
		return get("FA_INDEX");
	}
	
	public void setDoorIndex(java.lang.String doorIndex) {
		set("DOOR_INDEX", doorIndex);
	}

	public java.lang.String getDoorIndex() {
		return get("Door_INDEX");
	}

}
