package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBaseinfo<M extends BaseBaseinfo<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL", email);
	}

	public java.lang.String getEmail() {
		return get("EMAIL");
	}

	public void setIndustry(java.lang.String industry) {
		set("INDUSTRY", industry);
	}

	public java.lang.String getIndustry() {
		return get("INDUSTRY");
	}

	public void setCompany(java.lang.String company) {
		set("COMPANY", company);
	}

	public java.lang.String getCompany() {
		return get("COMPANY");
	}

	public void setSaleCompany(java.lang.String saleCompany) {
		set("SALE_COMPANY", saleCompany);
	}

	public java.lang.String getSaleCompany() {
		return get("SALE_COMPANY");
	}

	public void setSaleAdviser(java.lang.String saleAdviser) {
		set("SALE_ADVISER", saleAdviser);
	}

	public java.lang.String getSaleAdviser() {
		return get("SALE_ADVISER");
	}

	public void setSoftDiscount(java.math.BigDecimal softDiscount) {
		set("SOFT_DISCOUNT", softDiscount);
	}

	public java.math.BigDecimal getSoftDiscount() {
		return get("SOFT_DISCOUNT");
	}

	public void setFactoryCount(java.math.BigDecimal factoryCount) {
		set("FACTORY_COUNT", factoryCount);
	}

	public java.math.BigDecimal getFactoryCount() {
		return get("FACTORY_COUNT");
	}

	public void setIsBuyReport(java.lang.String isBuyReport) {
		set("IS_BUY_REPORT", isBuyReport);
	}

	public java.lang.String getIsBuyReport() {
		return get("IS_BUY_REPORT");
	}

	public void setCreatedate(java.util.Date createdate) {
		set("CREATEDATE", createdate);
	}

	public java.util.Date getCreatedate() {
		return get("CREATEDATE");
	}

	public void setUpdatedate(java.util.Date updatedate) {
		set("UPDATEDATE", updatedate);
	}

	public java.util.Date getUpdatedate() {
		return get("UPDATEDATE");
	}

}
