package com.logistics.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFactoryinfo<M extends BaseFactoryinfo<M>> extends Model<M> implements IBean {

	public void setId(java.math.BigDecimal id) {
		set("ID", id);
	}

	public java.math.BigDecimal getId() {
		return get("ID");
	}

	public void setBaseId(java.math.BigDecimal baseId) {
		set("BASE_ID", baseId);
	}

	public java.math.BigDecimal getBaseId() {
		return get("BASE_ID");
	}

	public void setFacName(java.lang.String facName) {
		set("FAC_NAME", facName);
	}

	public java.lang.String getFacName() {
		return get("FAC_NAME");
	}

	public void setItemInout(java.lang.String itemInout) {
		set("ITEM_INOUT", itemInout);
	}

	public java.lang.String getItemInout() {
		return get("ITEM_INOUT");
	}

	public void setWeiCount(java.lang.String weiCount) {
		set("WEI_COUNT", weiCount);
	}

	public java.lang.String getWeiCount() {
		return get("WEI_COUNT");
	}

	public void setTicCount(java.lang.String ticCount) {
		set("TIC_COUNT", ticCount);
	}

	public java.lang.String getTicCount() {
		return get("TIC_COUNT");
	}

	public void setMetCount(java.lang.String metCount) {
		set("MET_COUNT", metCount);
	}

	public java.lang.String getMetCount() {
		return get("MET_COUNT");
	}

	public void setIsNoduty(java.lang.String isNoduty) {
		set("IS_NODUTY", isNoduty);
	}

	public java.lang.String getIsNoduty() {
		return get("IS_NODUTY");
	}

	public void setNodMonitors(java.lang.String nodMonitors) {
		set("NOD_MONITORS", nodMonitors);
	}

	public java.lang.String getNodMonitors() {
		return get("NOD_MONITORS");
	}

	public void setTicHardware(java.lang.String ticHardware) {
		set("TIC_HARDWARE", ticHardware);
	}

	public java.lang.String getTicHardware() {
		return get("TIC_HARDWARE");
	}

	public void setFaIndex(java.lang.String faIndex) {
		set("FA_INDEX", faIndex);
	}

	public java.lang.String getFaIndex() {
		return get("FA_INDEX");
	}

	public void setMonHardware(java.lang.String monHardware) {
		set("MON_HARDWARE", monHardware);
	}

	public java.lang.String getMonHardware() {
		return get("MON_HARDWARE");
	}

	public void setQuaHardware(java.lang.String quaHardware) {
		set("QUA_HARDWARE", quaHardware);
	}

	public java.lang.String getQuaHardware() {
		return get("QUA_HARDWARE");
	}

	public void setIcRwCount(java.lang.String icRwCount) {
		set("IC_RW_COUNT", icRwCount);
	}

	public java.lang.String getIcRwCount() {
		return get("IC_RW_COUNT");
	}

	public void setIcCount(java.lang.String icCount) {
		set("IC_COUNT", icCount);
	}

	public java.lang.String getIcCount() {
		return get("IC_COUNT");
	}

	public void setMatHardware(java.lang.String matHardware) {
		set("MAT_HARDWARE", matHardware);
	}

	public java.lang.String getMatHardware() {
		return get("MAT_HARDWARE");
	}

	public void setPersonCount(java.lang.String personCount) {
		set("PERSON_COUNT", personCount);
	}

	public java.lang.String getPersonCount() {
		return get("PERSON_COUNT");
	}

}
