package com.logistics.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("BASEINFO", "ID", Baseinfo.class);
		arp.addMapping("FACTORYINFO", "ID", Factoryinfo.class);
		arp.addMapping("BLOG", "ID", Blog.class);
		// Composite Primary Key order: BASE_ID,FA_INDEX
		arp.addMapping("DOORHARDWARE", "ID", Doorhardware.class);
		arp.addMapping("WEIGHTHARDWARE", "ID", Weighthardware.class);
		arp.addMapping("EXCELUTIL", "NAME", ExcelUtil.class);
	}
}

