package com.logistics.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.logistics.common.model.base.BaseDoorhardware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Doorhardware extends BaseDoorhardware<Doorhardware> {
	public static final Doorhardware dao = new Doorhardware();
	
	public  List<Doorhardware> findByBaseIdAndIndex(int baseId,int index){
		return find("select * from doorhardware where base_id=? and fa_index=? order by door_index asc",baseId,index);
	}
	
	public void deleteByBaseIdAndIndex(int baseId,int index){
		Db.update("delete from doorhardware where base_id=? and fa_index=?",baseId,index);
	}
}
