package com.logistics.common.model;


import java.util.List;

import com.logistics.common.model.base.BaseFactoryinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Factoryinfo extends BaseFactoryinfo<Factoryinfo> {
	public static final Factoryinfo dao = new Factoryinfo();
	
	/**
	 * 
	 * @param base_id
	 * @param fa_index
	 * @return
	 */
	public Factoryinfo findByBaseIdAndIndex(int base_id,int fa_index){
		return findFirst("select * from factoryinfo where base_id=? and fa_index=?",base_id,fa_index);
	}
	
	public List<Factoryinfo> findAllByBaseId(int base_id){
		return find("select * from factoryinfo where base_id=?",base_id);
	}
}
