package com.logistics.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.logistics.common.model.base.BaseWeighthardware;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Weighthardware extends BaseWeighthardware<Weighthardware> {
	public static final Weighthardware dao = new Weighthardware();
	
	public  List<Weighthardware> findByBaseIdAndIndex(int baseId,int index){
		return find("select * from weighthardware where base_id=? and fa_index=? order by weight_index asc",baseId,index);
	}
	
	public void deleteByBaseIdAndIndex(int baseId,int index){
		Db.update("delete from weighthardware where base_id=? and fa_index=?",baseId,index);
	}
}
